from typing import Protocol
from app.models.reminder import Reminder
from app.schemas.reminder import ReminderCreate, ReminderUpdate

class IReminderService(Protocol):
    async def create_reminder(self, user_id: int, data: ReminderCreate) -> Reminder: ...
    async def get_user_reminders(self, user_id: int) -> list[Reminder]: ...
    async def get_reminder_by_id(self, reminder_id: int) -> Reminder: ...
    async def update_reminder(self, reminder_id: int, data: ReminderUpdate) -> Reminder: ...
    async def delete_reminder(self, reminder_id: int) -> None: ...